/**
 * PROMPT_DB 데이터 시드 스크립트
 * Google Sheets에서 가져온 프롬프트 데이터를 데이터베이스에 삽입
 */

const { initDatabase, getDb, closeDatabase } = require('../db/database');

// 마스터 프롬프트
const masterPrompts = [
  {
    prompt_key: 'MASTER_PROMPT',
    title: 'KSAT System Prompt',
    prompt_text: `[Role] You are an expert item writer for the Korean CSAT (KSAT) English test. Your task is to create exactly ONE test item in JSON format that strictly follows the MASTER schema and the item-specific instructions. Output ONLY a single JSON object (no code fences, no extra text). Required fields include: item_no, section (LC/RC), question, options (5), answer (1–5), explanation, and type-specific fields such as lc_script, passage, grammar_meta, gapped_passage, meta. Do not change the given passage text for RC. For LC, use lc_script for the listening script.`,
    active: 1
  },
  {
    prompt_key: 'PASSAGE_MASTER',
    title: 'KSAT Passage Generator',
    prompt_text: `[역할] 당신은 한국 수능 영어 지문을 쓰는 전문 출제위원입니다. 입력으로 주어지는 ITEM 유형, LEVEL(난이도), TOPIC(주제) 정보를 참고하여 KSAT 스타일의 영어 지문만 작성합니다. 지문에는 질문, 선택지, 밑줄, 빈칸, 해설 등을 절대 포함하지 않습니다. 여러 문단이 필요하면 문단 사이에 한 줄을 비워 구분합니다. TYPE(예: RC29/31/33, 세트 41–45 등)에 따라 요구되는 분량(단어 수)과 글의 성격(설명/논설)을 맞추되, 항상 자연스럽고 논리적인 영어 글을 생성합니다.`,
    active: 1
  }
];

// 문항별 프롬프트 (LC 1-17)
const lcPrompts = [
  { prompt_key: '1', title: 'LC1 Purpose', prompt_text: `[LC1 Purpose] Create a short 2–3 turn dialogue where the purpose of one speaker's speech can be inferred (e.g., to ask, to request, to confirm, to complain, to inform). Do NOT use explicit cues like "I'm calling to…". Question: "What is the purpose of the woman's (or man's) speech?" Provide 5 purpose options; only one must match the dialogue. Length: about 60–80 words.`, active: 1 },
  { prompt_key: '2', title: 'LC2 Location', prompt_text: `[LC2 Location] Generate a 2–3 turn conversation where the location is not named directly but is inferable from contextual clues (objects, actions, announcements). Question: "Where is the conversation most likely taking place?" Provide 5 location options; only one must be strongly supported. Length: 55–75 words.`, active: 1 },
  { prompt_key: '3', title: 'LC3 Relationship', prompt_text: `[LC3 Relationship] Generate a 2–3 turn conversation where the relationship between speakers (teacher–student, client–agent, buyer–seller, coworkers, etc.) is implied by tone and behavior, not explicitly stated. Question: "What is the relationship between the speakers?" Provide 5 relationship options; only one fits. Length: 55–80 words.`, active: 1 },
  { prompt_key: '4', title: 'LC4 Attitude/Feeling', prompt_text: `[LC4 Attitude] Create a conversation showing a clear emotional tone or attitude (relieved, disappointed, annoyed, grateful, worried) without naming it directly. Question: "How does the woman feel?" or "What is the man's attitude?" Provide 5 adjective options; one correct, others semantically close but wrong. Length: 60–80 words.`, active: 1 },
  { prompt_key: '5', title: 'LC5 True/Not Mentioned', prompt_text: `[LC5 Detail/True/NotMentioned] Write a 3-turn conversation including 3–4 key facts (time, place, plan, preference). Question: either "Which of the following is NOT mentioned?" or "Which statement is true according to the conversation?" Provide 5 statements; exactly one must satisfy the question type. Length: 65–90 words.`, active: 1 },
  { prompt_key: '6', title: 'LC6 Picture Matching', prompt_text: `[LC6 Picture Matching] Create a conversation that would match exactly one picture among five. In this system, each option is written as a short description of a picture. Question: "Which picture matches the conversation?" Provide 5 distinct descriptions; only one fully matches the dialogue. Length: 50–70 words.`, active: 1 },
  { prompt_key: '7', title: 'LC7 Main Topic', prompt_text: `[LC7 Topic] Write a dialogue in which two speakers discuss one main topic (e.g., planning an event, solving a problem, sharing an opinion). Question: "What are the speakers mainly talking about?" Provide 5 topic options; only one must summarize the conversation. Length: 55–80 words.`, active: 1 },
  { prompt_key: '8', title: 'LC8 Specific Detail', prompt_text: `[LC8 Detail] Construct a conversation that clearly includes a key detail (time, date, place, quantity, selected option). Question asks for this detail (e.g., "When will they meet?"). Provide 5 close options; only one matches. Length: 60–90 words.`, active: 1 },
  { prompt_key: '9', title: 'LC9 Next Action', prompt_text: `[LC9 Next Action] Create a dialogue where a logical next action of one speaker is implied by the discussion. Avoid explicit "I will now…" statements. Question: "What will the woman do next?" or similar. Provide 5 actions; only one naturally follows. Length: 60–85 words.`, active: 1 },
  { prompt_key: '10', title: 'LC10 Reason/Cause', prompt_text: `[LC10 Reason] Generate a conversation where a reason or cause (for being late, disappointed, worried, etc.) is implied. Question: "Why does the man feel disappointed?" or similar. Provide 5 possible reasons; only one is supported by the dialogue. Length: 60–85 words.`, active: 1 },
  { prompt_key: '11', title: 'LC11 Suggestion', prompt_text: `[LC11 Suggestion] Write a conversation where one speaker suggests or recommends something as a solution or idea. Question: "What does the woman suggest the man do?" Provide 5 suggestions; only one matches. Length: 60–90 words.`, active: 1 },
  { prompt_key: '12', title: 'LC12 Phone Message', prompt_text: `[LC12 Phone Message] Create a phone message or voicemail-style monologue: greeting → main message (info + request) → closing. Question: "What is the purpose of the message?" Provide 5 purpose options (ask for help, confirm, apologize, invite, inform of a change); one correct. Length: 70–95 words.`, active: 1 },
  { prompt_key: '13', title: 'LC13 Announcement/Ad', prompt_text: `[LC13 Announcement] Produce a short announcement/advertisement/notice (e.g., event, sale, schedule change, lost item). Question: "What is the announcement mainly about?" or "What is being advertised?" Provide 5 topic options; only one correct. Length: 60–90 words.`, active: 1 },
  { prompt_key: '14', title: 'LC14 Table/Chart Listening', prompt_text: `[LC14 Table/Chart Listening] Generate a conversation where speakers refer to simple quantitative info (prices, times, amounts). Question asks for a specific numerical fact. Provide 5 numeric options; only one is correct. Length: 65–95 words.`, active: 1 },
  { prompt_key: '15', title: 'LC15 Informational Speech', prompt_text: `[LC15 Informational Speech] Write a monologue-style informational speech or announcement (greeting → purpose → key points → closing). Question: "What is the main purpose of the announcement?" Provide 5 purpose options (inform, instruct, warn, invite, remind); one correct. Length: 80–110 words.`, active: 1 },
  { prompt_key: '16', title: 'LC16 Set Q1', prompt_text: `[LC16 Set Q1] This item is the first question of the LC16–17 listening set sharing a single lc_script. For item 16, create a question focusing on global meaning or key information of the shared script (topic, main idea, or important detail). Use only the shared script; do not create a new one here. Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '17', title: 'LC17 Set Q2', prompt_text: `[LC17 Set Q2] This item is the second question of the LC16–17 set. Create a question targeting a different aspect of the same shared lc_script (e.g., speaker's attitude, another detail, or next action). Ensure there is no overlap with LC16's focus. Provide 5 options; one correct.`, active: 1 }
];

// 문항별 프롬프트 (RC 18-45)
const rcPrompts = [
  { prompt_key: '18', title: 'RC18 Topic', prompt_text: `[RC18 Topic] Given the reading passage, create a question asking for the main topic or subject. Provide 5 options; only one should clearly capture the topic of the whole passage. Distractors should be related but too narrow, too broad, or off-focus. Do not modify the passage.`, active: 1 },
  { prompt_key: '19', title: 'RC19 Title', prompt_text: `[RC19 Title] Create a 'best title' question for the given passage. The correct title must concisely express the overall message. Distractors should be plausible but incomplete, overly specific, or overly general. Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '20', title: 'RC20 Gist', prompt_text: `[RC20 Gist] Make a question asking for the gist or core message of the passage. Provide 5 summary statements; only one must match the main point. Distractors may focus on supporting details or partial ideas.`, active: 1 },
  { prompt_key: '21', title: 'RC21 Purpose', prompt_text: `[RC21 Author's Purpose] Create a question about the author's purpose (to persuade, to criticize, to explain, to warn, to encourage, etc.). Provide 5 options in the form "To ~". Only one should match the overall intent of the passage.`, active: 1 },
  { prompt_key: '22', title: 'RC22 Emphasis', prompt_text: `[RC22 Emphasis] Produce a question asking what the author emphasizes in the passage. The correct option must represent the main argument or key emphasis. Distractors should represent secondary or background ideas.`, active: 1 },
  { prompt_key: '23', title: 'RC23 Claim', prompt_text: `[RC23 Claim] Create a question identifying the author's main claim or assertion. Provide 5 statements; only one must match the central claim supported by the passage.`, active: 1 },
  { prompt_key: '24', title: 'RC24 Function of Example', prompt_text: `[RC24 Function of Example] Create a question asking what role a specific example or illustration plays in the passage. Options should describe functions such as "to support the main idea", "to provide a contrast", "to give an explanation", "to show a consequence", etc.`, active: 1 },
  { prompt_key: '25', title: 'RC25 Chart/Graph', prompt_text: `[RC25 Chart/Graph] Using CHART_DATA provided in context, create a KSAT-style chart/graph interpretation item. Generate 5 statements about the chart; exactly one must be correct (or incorrect) according to the instructions. All numeric and comparative information must be logically consistent with CHART_DATA. Do not rewrite or alter the underlying data.`, active: 1 },
  { prompt_key: '26', title: 'RC26 Sentence-for-Blank', prompt_text: `[RC26 Sentence Blank] Create a question asking which sentence best fits a given blank in the passage. Provide 5 sentence options; only one must restore logical flow and coherence. Distractors should be locally plausible but globally inconsistent. Do not modify other sentences.`, active: 1 },
  { prompt_key: '27', title: 'RC27 Abstract Blank', prompt_text: `[RC27 Abstract Blank] Make a higher-level blank-completion question requiring abstract or conceptual inference. One option must integrate ideas before and after the blank in a meaningful way. Avoid trivial or purely factual completions. Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '28', title: 'RC28 Sentence Function/Transition', prompt_text: `[RC28 Function/Transition] Create a question asking how a specific underlined sentence functions in the passage (introducing a topic, contrasting, giving an example, summarizing, etc.). Provide 5 functional descriptions; only one fits the sentence in context.`, active: 1 },
  { prompt_key: '29', title: 'RC29 Grammar', prompt_text: `[RC29 Grammar] Based on the given passage with exactly 5 underlined segments (<u>...</u>), write a question asking which underlined part is grammatically incorrect or inappropriate. Provide 5 options corresponding to each underlined segment, answer (1–5), explanation, and grammar_meta (error type). Never change non-underlined text.`, active: 1 },
  { prompt_key: '30', title: 'RC30 Vocabulary-in-Context', prompt_text: `[RC30 Vocabulary] Create a vocabulary-in-context question about an underlined word/phrase. Provide 5 meaning options; one closest in meaning, others semantically related but incorrect. Avoid dictionary-style meta-language; stay within context.`, active: 1 },
  { prompt_key: '31', title: 'RC31 Single Blank', prompt_text: `[RC31 Single Blank] From the given passage, form a single-blank item by removing one key sentence or clause. Output gapped_passage (with a single [BLANK] or equivalent marker) and 5 completion options. Only one option must make the passage logically and semantically coherent. Do not alter non-blank text.`, active: 1 },
  { prompt_key: '32', title: 'RC32 Paragraph Summary', prompt_text: `[RC32 Summary] Create a question asking for the best summary of a specified paragraph or section. Provide 5 summary statements; only one accurately reflects the central content. Distractors must focus on partial or peripheral information.`, active: 1 },
  { prompt_key: '33', title: 'RC33 Long Single Blank', prompt_text: `[RC33 Long Single Blank] For a longer multi-paragraph passage, create a single-blank completion item that tests global logical flow. Provide 5 options; only one should maintain the deeper argument or reasoning. Academic/abstract style required.`, active: 1 },
  { prompt_key: '34', title: 'RC34 Sentence Insertion', prompt_text: `[RC34 Sentence Insertion] Design a sentence insertion item. Provide 5 sentence options; only one must fit at a marked insertion point in the passage, given pronoun reference, discourse markers, and logical order.`, active: 1 },
  { prompt_key: '35', title: 'RC35 Sentence Ordering', prompt_text: `[RC35 Ordering] Provide 5 choices representing different orders of 3–5 given scrambled sentences. Only one order should form a coherent paragraph. Ensure that temporal, causal, and referential cues support the correct sequence.`, active: 1 },
  { prompt_key: '36', title: 'RC36 Logical Completion', prompt_text: `[RC36 Logical Completion] Create a blank-completion item requiring higher-order logical inference (e.g., contrast, concession, cause–effect). The correct option must be consistent with both the local sentence and the global argument.`, active: 1 },
  { prompt_key: '37', title: 'RC37 Practical Reading', prompt_text: `[RC37 Practical Reading] Create a question based on a practical text (notice, flyer, schedule, instructions). Provide 5 options; only one matches explicit information in the text. Focus on realistic reading tasks.`, active: 1 },
  { prompt_key: '38', title: 'RC38 Rhetorical Structure', prompt_text: `[RC38 Structure] Make a question asking about the passage's overall organizational pattern (comparison-contrast, cause-effect, problem-solution, definition-example, etc.). Provide 5 structure labels or descriptions; one correct.`, active: 1 },
  { prompt_key: '39', title: 'RC39 Reference', prompt_text: `[RC39 Reference] Create a question asking what a pronoun or referring expression (it, they, this, such a phenomenon, etc.) refers to. Provide 5 candidate antecedents; only one is correct in context.`, active: 1 },
  { prompt_key: '40', title: 'RC40 Logical Flow', prompt_text: `[RC40 Logical Flow] Construct a question about the logical relation between ideas or paragraphs (e.g., cause–effect, contrast, elaboration, concession, sequence). Provide 5 descriptions; only one matches the relation in the passage.`, active: 1 },
  { prompt_key: '41', title: 'RC41 Set Q1', prompt_text: `[RC41 Set Q1] This is the first item of a two-question reading set (41–42) sharing one passage. For item 41, create a global comprehension question (main idea, best title, or author's purpose). The question must require understanding of the entire passage. Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '42', title: 'RC42 Set Q2', prompt_text: `[RC42 Set Q2] This is the second item of the 41–42 set. Using the same passage, create a question that focuses on a different skill (inference, specific detail, paragraph function, etc.). Ensure that RC42 does not duplicate the focus of RC41.`, active: 1 },
  { prompt_key: '43', title: 'RC43 Set Q1', prompt_text: `[RC43 Set Q1] This is the first item of a three-question reading set (43–45). Using the shared passage, create a global comprehension question (main idea, title, or purpose). Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '44', title: 'RC44 Set Q2', prompt_text: `[RC44 Set Q2] Using the same passage as RC43, create a question focusing on inference, detail, or author's attitude. Avoid overlap with RC43 and RC45. Provide 5 options; one correct.`, active: 1 },
  { prompt_key: '45', title: 'RC45 Set Q3', prompt_text: `[RC45 Set Q3] Using the same passage as RC43 and RC44, create a question about logical structure, sentence insertion, or partial summary. Ensure that the three questions together cover complementary aspects of the passage.`, active: 1 }
];

// 지문 생성 프롬프트 (P1-P45)
const passagePrompts = [
  { prompt_key: 'P1', title: 'LC01_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 1번(여자가 하는 말의 목적) 스타일의 대화를 쓰는 출제위원이다. '여자가 하는 말의 목적'을 파악할 수 있는 3~4턴짜리 짧은 대화를 영어로 작성하라. 화자는 Woman(W)과 Man(M) 두 사람이며, 마지막에 여자의 발화에 그녀의 의도(요청, 제안, 안내, 확인, 사과 등)가 분명히 드러나게 한다. 문제·보기·정답은 쓰지 말고 W:, M: 라벨을 붙인 영어 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P2', title: 'LC02_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 2번(남자의 의견/태도) 스타일의 대화를 쓰는 출제위원이다. '남자의 의견이나 태도'를 추론할 수 있는 3~4턴짜리 대화를 영어로 작성하라. 화자는 W와 M이며, 남자는 어떤 제안·상황·계획 등에 대해 자신의 태도(찬성, 반대, 걱정, 망설임 등)를 말로 드러내야 한다. 태도는 너무 직설적이지 않지만, 듣고 나면 한 가지로 추론 가능한 수준이어야 한다. 문제·보기·정답은 쓰지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P3', title: 'LC03_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 3번(여자의 말의 요지) 스타일의 대화를 쓰는 출제위원이다. 여자의 발화 전체의 핵심 내용(요지)을 파악할 수 있는 3~4턴짜리 대화를 영어로 작성하라. 여자는 자신의 생각이나 조언, 설명을 비교적 길게 말하고, 남자는 짧게 반응한다. 세부 예시는 1~2개만 포함하고, 전체 메시지가 하나의 요지로 정리될 수 있도록 구성한다. 문제·보기·정답은 쓰지 말고 W:, M: 라벨을 붙인 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P4', title: 'LC04_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 4번(그림/장면 일치) 스타일의 대화를 쓰는 출제위원이다. 어떤 그림 또는 장면과 일치 여부를 판단할 수 있는 3~4턴짜리 영어 대화를 작성하라. 두 화자는 사람·사물의 위치, 행동, 복장, 개수 등 시각적 요소를 3~5개 정도 언급한다. 대화를 들으면 한 가지 장면이 떠오르도록 구체적으로 표현하되 지나치게 복잡하게 만들지 않는다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P5', title: 'LC05_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 5번(대화 후 남자가 할 일) 스타일의 대화를 쓰는 출제위원이다. 대화가 끝난 뒤 남자가 앞으로 할 일을 한 가지로 추론할 수 있는 3~4턴짜리 영어 대화를 작성하라. 두 화자는 일정, 약속, 준비물, 장소 이동 등과 관련된 내용을 이야기하고, 마지막 부분에서 남자가 무엇을 하기로 결정하는지 분명히 드러나게 한다. 문제·보기·정답은 쓰지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P6', title: 'LC06_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 6번(지불할 금액) 스타일의 대화를 쓰는 출제위원이다. 두 사람이 물건이나 서비스의 가격, 수량, 할인, 쿠폰, 세금 등을 이야기하는 3~4턴짜리 영어 대화를 작성하라. 대화 속 정보만으로 최종 지불해야 할 금액을 계산할 수 있어야 한다. 숫자와 단위($, dollars, won 등)를 자연스럽게 포함하고, 계산 과정이 한 번에 추론 가능하도록 정보를 제공한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P7', title: 'LC07_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 7번(참석 불가 이유) 스타일의 대화를 쓰는 출제위원이다. 두 사람이 어떤 행사나 모임, 약속에 대해 이야기하면서 남자 또는 여자가 참석하지 못하는 이유를 설명하는 3~4턴짜리 영어 대화를 작성하라. 일정 충돌, 건강, 교통, 가족 행사 등 일상적인 이유를 사용하며, 마지막에는 불참 이유가 한 가지로 명확히 드러나야 한다. 문제·보기·정답은 쓰지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P8', title: 'LC08_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 8번(안내문에서 언급되지 않은 정보) 스타일의 대화를 쓰는 출제위원이다. 두 사람이 어떤 행사 안내문, 광고, 게시물 등을 보고 대화를 나누는 상황을 영어로 작성하라. 대화 속에서 안내문에 적혀 있는 정보와 적혀 있지 않은 정보를 구분할 수 있어야 한다. 안내문에 포함될 만한 정보(시간, 장소, 대상, 조건 등)를 3~5개 정도 언급하되, 일부 정보는 의도적으로 빠져 있도록 구성한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P9', title: 'LC09_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 9번(실용문 내용 불일치) 스타일의 지문을 쓰는 출제위원이다. 어떤 공지, 광고, 안내, 이메일 등 실용문 한 편을 영어로 작성하라. 수험생은 이후 제시되는 진술 중 어느 것이 지문 내용과 일치하지 않는지를 찾게 된다. 따라서 사실 정보(날짜, 장소, 조건, 대상, 금액 등)를 4~6개 정도 포함하고, 서로 혼동될 수 있는 요소도 일부 넣되 모순은 만들지 않는다. 길이는 약 120~150단어로 하고, 실용문 형식을 유지한다.`, active: 1 },
  { prompt_key: 'P10', title: 'LC10_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 10번(표 정보 선택) 스타일의 지문을 쓰는 출제위원이다. 표 또는 일정표와 함께 제시될 짧은 설명문을 영어로 작성하라. 설명문에는 일정, 프로그램, 좌석, 가격대 등 표의 항목과 연결되는 정보가 포함되어야 한다. 수험생은 듣기 후 표에서 알맞은 항목을 선택할 수 있어야 하므로, 서로 다른 선택지를 구분할 수 있을 만큼 구체적으로 정보를 제시한다. 길이는 약 100~130단어로 한다.`, active: 1 },
  { prompt_key: 'P11', title: 'LC11_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 11번(마지막 말에 대한 응답, 3점) 스타일의 대화를 쓰는 출제위원이다. 대화의 마지막에 한 사람이 말한 내용에 대해 적절한 응답을 고를 수 있는 3~4턴짜리 영어 대화를 작성하라. 마지막 화자의 발화는 상황과 감정, 의도 등이 드러나도록 하고, 그에 어울리는 다양한 응답이 떠오를 수 있도록 약간 복합적인 맥락을 제공한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P12', title: 'LC12_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 12번(마지막 말에 대한 응답) 스타일의 대화를 쓰는 출제위원이다. 일상적이고 비교적 간단한 상황에서 마지막 화자의 말에 어울리는 응답을 고를 수 있는 3~4턴짜리 영어 대화를 작성하라. 맥락은 너무 복잡하지 않게 하되, 단순 암기가 아니라 상황 이해가 필요하도록 구성한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P13', title: 'LC13_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 13번(마지막 말에 대한 응답) 스타일의 대화를 쓰는 출제위원이다. 학교, 동아리, 친구 사이 등의 상황에서 마지막 화자의 말에 대한 적절한 응답을 고를 수 있는 3~4턴짜리 영어 대화를 작성하라. 화자들의 관계와 상황이 자연스럽게 드러나도록 하고, 마지막 말은 의문, 제안, 감사, 사과, 위로 등 여러 유형이 가능하도록 구성한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P14', title: 'LC14_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 14번(마지막 말에 대한 응답, 3점) 스타일의 대화를 쓰는 출제위원이다. 직장, 진로, 프로젝트, 동아리 활동 등 비교적 복잡한 상황에서 마지막 화자의 말에 대한 적절한 응답을 고를 수 있는 3~4턴짜리 영어 대화를 작성하라. 대화 중에 여러 정보와 감정이 섞여 있어, 마지막 말을 이해하려면 앞 내용을 종합해야 한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P15', title: 'LC15_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 15번(상황 설명에 대한 반응, 3점) 스타일의 대화를 쓰는 출제위원이다. 한 화자가 자신의 상황이나 문제를 설명하고, 다른 화자가 적절한 반응을 보이는 3~4턴짜리 영어 대화를 작성하라. 상황 설명에는 시간 제약, 선택의 갈등, 예기치 못한 사건 등이 포함될 수 있으며, 이를 이해해야 올바른 반응을 고를 수 있도록 구성한다. 문제·보기·정답은 만들지 말고 W:, M: 형식의 대화만 출력한다.`, active: 1 },
  { prompt_key: 'P16', title: 'LC16_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 16·17번 세트 지문(주제/언급X) 스타일의 공통 지문을 쓰는 출제위원이다. 한 편의 비교적 짧은 설명문 또는 인터뷰 스크립트를 영어로 작성하라. 이 지문은 16번에서 전체 주제를 묻고, 17번에서 지문에서 언급되지 않은 정보를 묻는 데 사용된다. 주제는 하나로 명확해야 하며, 세부 정보는 4~6개 정도 포함한다. 길이는 약 150~180단어로 하고, 질문·보기·정답은 포함하지 않는다.`, active: 1 },
  { prompt_key: 'P17', title: 'LC17_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 듣기 16·17번 세트 지문과 동일한 유형의 공통 지문을 쓰는 출제위원이다. 실제 시스템에서는 보통 16번에서 생성한 지문을 재사용하므로, 이 프롬프트도 16번과 동일한 형식의 설명문 또는 인터뷰 스크립트를 상정한다. 주제는 하나로 통일하고, 세부 정보는 4~6개 정도 포함하며, 길이는 약 150~180단어로 한다. 질문·보기·정답은 포함하지 않는다.`, active: 1 },
  { prompt_key: 'P18', title: 'RC18_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC18(안내문의 목적) 문항용 실용문을 쓰는 출제위원이다. 행사 안내, 서비스 변경, 프로그램 신청, 규정 변경 등 안내문의 전형적인 상황 중 하나를 선택하여 영어 안내문을 작성하라. 안내문의 전체 목적이 하나로 명확하게 정리될 수 있어야 하며, 시간·장소·대상·조건 등 사실 정보를 3~5개 정도 포함한다. 길이는 약 110~150단어로 하고, 제목은 쓰지 말며 본문만 작성한다.`, active: 1 },
  { prompt_key: 'P19', title: 'RC19_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC19(심경 변화) 문항용 지문을 쓰는 출제위원이다. 한 인물이 겪는 사건과 그에 따른 감정 변화를 추론할 수 있는 짧은 내러티브를 영어로 작성하라. 글 앞부분에서는 인물의 초기 감정을 암시적으로, 뒷부분에서는 달라진 감정을 비교적 분명하게 드러내며, 사건은 일상적이되 의미 있는 변화의 계기가 되어야 한다. 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P20', title: 'RC20_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC20(필자의 주장) 문항용 논설문을 쓰는 출제위원이다. 교육, 사회, 환경, 기술, 인간관계 등 일반적인 주제 중 하나를 선택하여 필자의 주장을 분명히 드러내는 글을 영어로 작성하라. 도입부에서 문제를 제기하고, 본문에서 근거 2~3개를 제시하며, 결론에서 주장을 다시 정리한다. 주장은 글 전체에서 일관되게 유지되어야 한다. 길이는 약 150~180단어로 한다.`, active: 1 },
  { prompt_key: 'P21', title: 'RC21_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC21(비유적 표현/함축 의미) 문항용 지문을 쓰는 출제위원이다. 한두 개의 비유적 표현이나 은유, 상징적 표현을 포함한 단락을 영어로 작성하라. 수험생은 문맥을 통해 그 표현의 의미를 추론해야 하며, 비유가 글의 주제와 자연스럽게 연결되어야 한다. 글의 길이는 약 130~160단어이며, 비유적 표현은 지나치게 난해하지 않게 한다.`, active: 1 },
  { prompt_key: 'P22', title: 'RC22_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC22(요지) 문항용 지문을 쓰는 출제위원이다. 글 전체의 핵심 메시지가 하나로 통일된 단락을 영어로 작성하라. 주제는 교육, 인간관계, 환경, 기술, 진로 등 일반적인 범위에서 선택하고, 예시나 세부 사항은 그 핵심 메시지를 뒷받침하는 수준으로만 사용한다. 요지는 문단의 첫 문장 또는 마지막 문장에서 자연스럽게 드러나도록 하고, 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P23', title: 'RC23_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC23(내용 전개/사회·경제 주제) 문항용 지문을 쓰는 출제위원이다. 사회·경제·노동·기술 변화 등과 관련된 주제를 선택하여 하나의 주장 또는 관점을 중심으로 글을 영어로 작성하라. 글은 원인–결과, 문제–해결, 비교–대조 등의 구조 중 하나를 사용해 전개하며, 핵심 아이디어는 하나로 일관되게 유지한다. 길이는 약 150~180단어로 한다.`, active: 1 },
  { prompt_key: 'P24', title: 'RC24_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC24(제목) 문항용 지문을 쓰는 출제위원이다. 글 전체를 하나의 제목으로 요약할 수 있는 단락을 영어로 작성하라. 도입에서 주제를 소개하고, 본문에서 관련 이유·예시를 2~3개 제시하며, 마지막에서 중심 메시지를 다시 강조한다. 글 곳곳에서 같은 핵심 개념이 반복되어 제목을 고르기 쉽게 해야 한다. 길이는 약 120~150단어로 한다.`, active: 1 },
  { prompt_key: 'P25', title: 'RC25_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC25(도표/그래프) 문항용 지문을 쓰는 출제위원이다. 이미 주어진 그래프나 표를 설명하는 짧은 영어 설명문을 작성한다고 가정하라. 도표의 제목, 축, 범주, 추세 등을 자연스럽게 언급하며, 비교나 증감 표현을 포함한다. 수험생은 진술 5개 중 도표와 일치하는 것을 고르게 되므로, 설명문은 도표의 전반적인 특징과 일부 구체적 수치를 함께 전달해야 한다. 길이는 약 120~150단어로 한다.`, active: 1 },
  { prompt_key: 'P26', title: 'RC26_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC26(사실 여부 판단) 문항용 지문을 쓰는 출제위원이다. 한 인물, 단체, 제도, 물건 등을 소개하는 설명문을 영어로 작성하라. 이름, 역할, 특징, 활동, 시기 등 사실 정보를 4~6개 정도 포함하고, 서로 비교될 수 있는 요소를 적절히 섞는다. 수험생은 이후 진술이 지문 내용과 일치하는지 판단하게 되므로, 정보는 분명하되 너무 단순하지 않게 구성한다. 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P27', title: 'RC27_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC27(실용문 일치, 패스 카드 등) 문항용 지문을 쓰는 출제위원이다. 특정 서비스, 멤버십, 패스 카드, 이용권 등을 설명하는 실용문을 영어로 작성하라. 사용 조건, 가격 구간, 혜택, 예외 사항 등을 4~6개 정도 포함하고, 서로 헷갈릴 수 있는 부분도 일부 포함한다. 길이는 약 120~150단어로 하고, 표나 그림 없이 본문만 작성한다.`, active: 1 },
  { prompt_key: 'P28', title: 'RC28_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC28(실용문 일치, 안내/홍보) 문항용 지문을 쓰는 출제위원이다. 축제, 전시, 캠프, 워크숍 등 이벤트를 홍보하는 실용문을 영어로 작성하라. 날짜, 장소, 프로그램 구성, 신청 방법, 대상, 주의 사항 등 정보를 4~6개 정도 포함한다. 수험생은 이후 진술이 지문과 일치하는지 확인하게 되므로, 정보는 분명하고도 서로 구별 가능해야 한다. 길이는 약 120~150단어로 한다.`, active: 1 },
  { prompt_key: 'P29', title: 'RC29_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC29(어법) 문항용 지문을 쓰는 출제위원이다. 3~4문장으로 이루어진 짧은 단락을 영어로 작성하되, 각 문장에는 시제, 주어-동사 일치, 대명사, 분사/부정사, 접속사 등 서로 다른 문법 포인트가 포함되도록 한다. 이 단계에서는 모든 문장을 문법적으로 올바르게 작성하고, 밑줄이나 번호는 사용하지 않는다. 이후 단계에서 이 지문을 바탕으로 밑줄 5개 중 하나만 틀리도록 변형할 것이다. 길이는 약 60~90단어로 한다.`, active: 1 },
  { prompt_key: 'P30', title: 'RC30_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC30(문맥상 부적절한 단어) 문항용 지문을 쓰는 출제위원이다. 하나의 주제를 중심으로 자연스럽게 전개되는 단락을 영어로 작성하라. 각 문장은 의미상 연결이 되어야 하고, 특정 위치에 문맥상 어울리지 않는 단어 하나를 넣을 수 있는 구조가 되도록 작성한다. 이 단계에서는 모든 단어를 자연스럽게 맞는 단어로 쓰고, 이후 단계에서 한 단어를 문맥에 어울리지 않는 단어로 교체할 것이다. 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P31', title: 'RC31_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC31(단일 빈칸) 문항용 지문을 쓰는 출제위원이다. 교육, 습관, 인간 행동, 협력 등 일반적인 주제를 선택하여 한 단락의 글을 영어로 작성하라. 글의 전개 과정에서 핵심 아이디어를 요약하거나 전환하는 문장을 1개 포함시키고, 그 문장이 나중에 빈칸이 될 수 있도록 논리적으로 중요한 위치에 배치한다. 이 단계에서는 빈칸 없이 완전한 문장으로 작성하며, 길이는 약 120~150단어로 한다.`, active: 1 },
  { prompt_key: 'P32', title: 'RC32_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC32(고난도 단일 빈칸) 문항용 지문을 쓰는 출제위원이다. 교육 정책, 사회 변화, 사고력, 창의성 등 비교적 추상적인 주제를 선택하여 한 단락 또는 두 단락으로 영어 글을 작성하라. 글에는 개념 정의, 대비, 예시 등이 포함되어야 하며, 논리 전개상 중요한 역할을 하는 문장을 1개 포함시킨다. 이 문장은 나중에 빈칸으로 바뀔 예정이다. 이 단계에서는 빈칸 없이 완전한 문장으로 작성하고, 길이는 약 140~170단어로 한다.`, active: 1 },
  { prompt_key: 'P33', title: 'RC33_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC33(장문 빈칸) 문항용 지문을 쓰는 출제위원이다. 서론–본론–결론 구조를 가진 3~4문단짜리 논설문 또는 설명문을 영어로 작성하라. 서론에서 주제를 제시하고, 본론에서 관련된 근거·예시·비교를 2~3개 제시하며, 결론에서 핵심 메시지를 다시 정리한다. 본론이나 결론 부분에는 나중에 빈칸으로 만들 수 있는 핵심 문장을 1개 이상 포함해야 한다. 이 단계에서는 빈칸 없이 완전한 글로 작성하고, 길이는 약 220~260단어로 한다.`, active: 1 },
  { prompt_key: 'P34', title: 'RC34_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC34(규칙·역할 관련 단일 빈칸) 문항용 지문을 쓰는 출제위원이다. 규칙, 역할, 책임, 질서, 공정성 등과 관련된 상황이나 제도를 설명하는 한 단락짜리 글을 영어로 작성하라. 글에는 규칙의 필요성, 역할 분담, 기대되는 행동 등이 포함되고, 나중에 빈칸으로 만들 핵심 문장이 1개 있어야 한다. 이 단계에서는 완전한 문장으로만 작성하며, 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P35', title: 'RC35_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC35(문장 삭제) 문항용 지문을 쓰는 출제위원이다. 여러 문장으로 이루어진 한 단락의 글을 영어로 작성하되, 그 중 한 문장은 삭제해도 글의 흐름에 문제가 없거나 오히려 더 좋아지는 '불필요한 문장'이 되도록 설계하라. 다른 문장들은 하나의 중심 아이디어를 향해 논리적으로 연결되어야 한다. 이 단계에서는 불필요한 문장을 포함한 완전한 단락을 작성하고, 길이는 약 140~170단어로 한다.`, active: 1 },
  { prompt_key: 'P36', title: 'RC36_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC36(문장 배열) 문항용 지문을 쓰는 출제위원이다. 5~6개의 문장으로 구성된 글을 영어로 작성하되, 각 문장은 명확한 순서에 따라 논리적으로 이어져야 한다. 도입, 전개, 예시, 결론 등의 구성 요소가 분명하여 문장 순서가 바뀌면 글의 의미가 어색해지도록 설계한다. 이 단계에서는 올바른 순서대로 한 단락으로 작성하며, 길이는 약 130~160단어로 한다.`, active: 1 },
  { prompt_key: 'P37', title: 'RC37_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC37(고난도 문장 배열, 3점) 문항용 지문을 쓰는 출제위원이다. 비교적 추상적인 주제를 다루는 5~6개 문장의 글을 영어로 작성하라. 각 문장은 논증의 단계(문제 제기, 주장, 근거, 예시, 반론, 결론 등)를 나타내며, 순서가 바뀌면 논리 구조가 무너져야 한다. 이 단계에서는 올바른 순서대로 한 단락으로 작성하고, 길이는 약 150~180단어로 한다.`, active: 1 },
  { prompt_key: 'P38', title: 'RC38_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC38(문장 삽입) 문항용 지문을 쓰는 출제위원이다. 하나의 단락 또는 두 단락으로 이루어진 영어 글을 작성하되, 특정 위치에만 자연스럽게 들어갈 수 있는 문장을 상정하여 글을 설계하라. 글에는 주제 문장, 세부 설명, 예시, 결론 등이 있고, 삽입 문장은 그 중 일부를 연결하거나 부연하는 역할을 한다. 이 단계에서는 삽입될 문장을 따로 쓰지 않고, 삽입 위치 후보가 분명히 보이도록 전체 글만 작성한다. 길이는 약 140~170단어로 한다.`, active: 1 },
  { prompt_key: 'P39', title: 'RC39_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC39(고난도 문장 삽입) 문항용 지문을 쓰는 출제위원이다. 개념적·추상적 내용을 다루는 2단락 내외의 영어 글을 작성하라. 두 단락 또는 여러 문장 사이의 논리적 연결 관계가 중요하며, 특정 위치에 들어갈 문장이 논리적 연결을 담당하도록 설계한다. 이 단계에서는 전체 글만 작성하고, 삽입 문장은 따로 쓰지 않는다. 길이는 약 150~190단어로 한다.`, active: 1 },
  { prompt_key: 'P40', title: 'RC40_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC40(요약) 문항용 장문을 쓰는 출제위원이다. 서론–본론–결론 구조를 가진 2~3단락짜리 글을 영어로 작성하라. 글 전체는 하나의 핵심 메시지로 요약될 수 있어야 하며, 본문에는 그 핵심을 뒷받침하는 이유·예시·비교 등이 2~3개 포함된다. 결론 부분에서는 요약 선택지로 사용할 수 있는 문장을 1개 이상 포함한다. 길이는 약 180~220단어로 한다.`, active: 1 },
  { prompt_key: 'P41_45', title: 'RC41_45_PASSAGE_GEN', prompt_text: `당신은 한국 수능 영어 RC41~45 세트 문항용 공통 지문을 쓰는 출제위원이다. 장문 세트에서 제목/중심 내용, 어휘/표현, 문장 순서, 지시어, 내용 일치 여부를 모두 평가할 수 있도록 서론–본론–결론 구조를 가진 3~5단락짜리 글을 영어로 작성하라. 서론에서는 주제와 관점을 소개하고, 본론에서는 관련 아이디어나 예시를 3개 정도 제시하며, 결론에서는 핵심 메시지를 정리한다. 글 안에는 this, that, they, such, these 등의 지시어나 연결 표현이 자연스럽게 포함되어야 하며, 문단과 문장 사이의 논리 흐름이 뚜렷해야 한다. 길이는 약 350~420단어로 한다.`, active: 1 }
];

// 비활성화된 프롬프트 (옵션)
const inactivePrompts = [
  { prompt_key: 'P41', title: 'RC41_PASSAGE_GEN(PER_ITEM)', prompt_text: `(옵션) 세트 41~42에서 41번 문항만을 위한 추가 지문 지침이 필요할 경우 사용한다. 일반적으로는 RC41_45_PASSAGE_GEN으로 생성된 공통 지문을 사용하므로, 이 행은 비활성화하거나 공통 지침과 동일하게 둘 수 있다.`, active: 0 },
  { prompt_key: 'P42', title: 'RC42_PASSAGE_GEN(PER_ITEM)', prompt_text: `(옵션) 세트 41~42에서 42번 문항만을 위한 추가 지문 지침이 필요할 경우 사용한다. 대부분의 경우 RC41_45_PASSAGE_GEN으로 생성된 공통 지문을 사용하므로, 이 행은 비활성화하거나 공통 지침과 동일하게 둘 수 있다.`, active: 0 },
  { prompt_key: 'P43', title: 'RC43_PASSAGE_GEN(PER_ITEM)', prompt_text: `(옵션) 세트 43~45에서 43번 문항만을 위한 추가 지문 지침이 필요할 경우 사용한다. 기본적으로는 RC41_45_PASSAGE_GEN으로 생성된 공통 지문을 사용하므로, 이 행은 비활성화 상태로 두어도 된다.`, active: 0 },
  { prompt_key: 'P44', title: 'RC44_PASSAGE_GEN(PER_ITEM)', prompt_text: `(옵션) 세트 43~45에서 44번 문항만을 위한 추가 지문 지침이 필요할 경우 사용한다. 기본적으로는 RC41_45_PASSAGE_GEN으로 생성된 공통 지문을 사용하므로, 이 행은 비활성화 상태로 두어도 된다.`, active: 0 },
  { prompt_key: 'P45', title: 'RC45_PASSAGE_GEN(PER_ITEM)', prompt_text: `(옵션) 세트 43~45에서 45번 문항만을 위한 추가 지문 지침이 필요할 경우 사용한다. 기본적으로는 RC41_45_PASSAGE_GEN으로 생성된 공통 지문을 사용하므로, 이 행은 비활성화 상태로 두어도 된다.`, active: 0 }
];

// 모든 프롬프트 합치기
const allPrompts = [
  ...masterPrompts,
  ...lcPrompts,
  ...rcPrompts,
  ...passagePrompts,
  ...inactivePrompts
];

async function seedPrompts() {
  try {
    await initDatabase();
    const db = getDb();

    console.log('PROMPT_DB 데이터 삽입 시작...');

    // 기존 프롬프트 삭제 (새로 시드)
    db.exec('DELETE FROM prompts');

    const insertStmt = db.prepare(`
      INSERT INTO prompts (prompt_key, title, prompt_text, active)
      VALUES (?, ?, ?, ?)
    `);

    let insertedCount = 0;
    for (const prompt of allPrompts) {
      insertStmt.run(
        prompt.prompt_key,
        prompt.title,
        prompt.prompt_text,
        prompt.active
      );
      insertedCount++;
    }

    console.log(`✅ ${insertedCount}개의 PROMPT 데이터 삽입 완료`);

    // 통계 출력
    const stats = db.prepare(`
      SELECT
        CASE WHEN active = 1 THEN 'Active' ELSE 'Inactive' END as status,
        COUNT(*) as count
      FROM prompts
      GROUP BY active
    `).all();

    console.log('\n📊 상태별 통계:');
    stats.forEach(s => console.log(`  - ${s.status}: ${s.count}개`));

    // 카테고리별 통계
    console.log('\n📊 카테고리별 통계:');
    console.log(`  - Master Prompts: ${masterPrompts.length}개`);
    console.log(`  - LC Prompts (1-17): ${lcPrompts.length}개`);
    console.log(`  - RC Prompts (18-45): ${rcPrompts.length}개`);
    console.log(`  - Passage Prompts (P1-P45): ${passagePrompts.length}개`);
    console.log(`  - Inactive Prompts: ${inactivePrompts.length}개`);

    closeDatabase();
    console.log('\n데이터베이스 연결 종료');

  } catch (error) {
    console.error('시드 오류:', error);
    process.exit(1);
  }
}

seedPrompts();
