/**
 * ITEM_JSON 데이터 시드 스크립트
 * Google Sheets에서 가져온 생성 결과 데이터를 데이터베이스에 삽입
 */

const { initDatabase, getDb, closeDatabase } = require('../db/database');

const itemJsonData = [
  {
    request_id: 'R-0001',
    raw_json: '{"passage":"In the early stages of learning, children often rely heavily on their senses to understand the world around them. According to developmental psychologist Jean Piaget, this sensory exploration is a fundamental part of cognitive development. Through touching, tasting, and observing objects, children begin to form mental schemas—internal frameworks that help them organize and interpret information. As they grow, these schemas become more complex, allowing children to engage in abstract thinking and problem-solving. However, the foundation laid during early sensory experiences remains crucial, as it shapes how individuals process and respond to new information throughout their lives.","question":"What is the main idea of the passage?","options":["Children learn primarily through memorization in their early years.","Sensory experiences in childhood form the basis for cognitive development.","Jean Piaget believed that abstract thinking develops before sensory exploration.","Mental schemas are only important for problem-solving in adulthood.","Cognitive development is complete by the time children reach school age."],"answer":2,"explanation":"The passage discusses how children\'s early sensory experiences help form mental schemas, which are foundational for cognitive development and continue to influence learning throughout life."}',
    normalized_json: '{"passage":"In the early stages of learning, children often rely heavily on their senses to understand the world around them. According to developmental psychologist Jean Piaget, this sensory exploration is a fundamental part of cognitive development. Through touching, tasting, and observing objects, children begin to form mental schemas—internal frameworks that help them organize and interpret information. As they grow, these schemas become more complex, allowing children to engage in abstract thinking and problem-solving. However, the foundation laid during early sensory experiences remains crucial, as it shapes how individuals process and respond to new information throughout their lives.","question":"What is the main idea of the passage?","options":["Children learn primarily through memorization in their early years.","Sensory experiences in childhood form the basis for cognitive development.","Jean Piaget believed that abstract thinking develops before sensory exploration.","Mental schemas are only important for problem-solving in adulthood.","Cognitive development is complete by the time children reach school age."],"answer":2,"explanation":"The passage discusses how children\'s early sensory experiences help form mental schemas, which are foundational for cognitive development and continue to influence learning throughout life."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중',
    distractor_score: '4',
    final_json: '{"passage":"In the early stages of learning, children often rely heavily on their senses to understand the world around them. According to developmental psychologist Jean Piaget, this sensory exploration is a fundamental part of cognitive development. Through touching, tasting, and observing objects, children begin to form mental schemas—internal frameworks that help them organize and interpret information. As they grow, these schemas become more complex, allowing children to engage in abstract thinking and problem-solving. However, the foundation laid during early sensory experiences remains crucial, as it shapes how individuals process and respond to new information throughout their lives.","question":"What is the main idea of the passage?","options":["Children learn primarily through memorization in their early years.","Sensory experiences in childhood form the basis for cognitive development.","Jean Piaget believed that abstract thinking develops before sensory exploration.","Mental schemas are only important for problem-solving in adulthood.","Cognitive development is complete by the time children reach school age."],"answer":2,"explanation":"The passage discusses how children\'s early sensory experiences help form mental schemas, which are foundational for cognitive development and continue to influence learning throughout life."}'
  },
  {
    request_id: 'R-0007',
    raw_json: '{"passage":"Good morning, everyone. Before we begin today\'s workshop on digital marketing strategies, I\'d like to remind you of a few important points. First, please make sure your phones are on silent mode to avoid any disruptions during the presentations. Second, we will have a 15-minute coffee break at 10:30, during which refreshments will be served in the lobby. Third, if you have any questions for the speakers, please write them down on the cards provided at your seats, and we will address them during the Q&A session at the end of each presentation. Finally, please note that today\'s workshop is being recorded for training purposes, so your participation implies consent to being filmed. Thank you for your cooperation, and let\'s have a productive session.","question":"What is the purpose of this announcement?","options":["To introduce the keynote speaker","To explain workshop guidelines and logistics","To promote a new marketing product","To announce a schedule change","To conclude the workshop"],"answer":2,"explanation":"The announcement provides practical information about phone etiquette, break times, how to ask questions, and recording consent—all guidelines for workshop participants."}',
    normalized_json: '{"passage":"Good morning, everyone. Before we begin today\'s workshop on digital marketing strategies, I\'d like to remind you of a few important points. First, please make sure your phones are on silent mode to avoid any disruptions during the presentations. Second, we will have a 15-minute coffee break at 10:30, during which refreshments will be served in the lobby. Third, if you have any questions for the speakers, please write them down on the cards provided at your seats, and we will address them during the Q&A session at the end of each presentation. Finally, please note that today\'s workshop is being recorded for training purposes, so your participation implies consent to being filmed. Thank you for your cooperation, and let\'s have a productive session.","question":"What is the purpose of this announcement?","options":["To introduce the keynote speaker","To explain workshop guidelines and logistics","To promote a new marketing product","To announce a schedule change","To conclude the workshop"],"answer":2,"explanation":"The announcement provides practical information about phone etiquette, break times, how to ask questions, and recording consent—all guidelines for workshop participants."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '하',
    distractor_score: '3',
    final_json: '{"passage":"Good morning, everyone. Before we begin today\'s workshop on digital marketing strategies, I\'d like to remind you of a few important points. First, please make sure your phones are on silent mode to avoid any disruptions during the presentations. Second, we will have a 15-minute coffee break at 10:30, during which refreshments will be served in the lobby. Third, if you have any questions for the speakers, please write them down on the cards provided at your seats, and we will address them during the Q&A session at the end of each presentation. Finally, please note that today\'s workshop is being recorded for training purposes, so your participation implies consent to being filmed. Thank you for your cooperation, and let\'s have a productive session.","question":"What is the purpose of this announcement?","options":["To introduce the keynote speaker","To explain workshop guidelines and logistics","To promote a new marketing product","To announce a schedule change","To conclude the workshop"],"answer":2,"explanation":"The announcement provides practical information about phone etiquette, break times, how to ask questions, and recording consent—all guidelines for workshop participants."}'
  },
  {
    request_id: 'R-0010',
    raw_json: '{"dialogue":{"W":"Hi, I\'m looking for a birthday gift for my daughter. She\'s turning 10 next week.","M":"Great! We have a variety of options. Does she have any particular interests?","W":"She loves art and drawing. Do you have any art supplies?","M":"Yes, we have several art kits. This deluxe set includes colored pencils, markers, and a sketchbook. It\'s $35.","W":"That sounds perfect! I\'ll take it. Can you gift wrap it?","M":"Of course. Gift wrapping is complimentary. Would you like a card as well?","W":"Yes, please. How much extra is the card?","M":"Cards are $3 each. We have several designs to choose from.","W":"I\'ll take one with balloons on it.","M":"Excellent choice. Your total will be $38."},"question":"What is the woman going to purchase?","options":["An art kit only","An art kit and gift wrapping","An art kit, gift wrapping, and a card","A sketchbook and markers","Colored pencils and a card"],"answer":3,"explanation":"The woman purchases the deluxe art kit ($35) with complimentary gift wrapping and adds a card ($3), making her total $38."}',
    normalized_json: '{"dialogue":{"W":"Hi, I\'m looking for a birthday gift for my daughter. She\'s turning 10 next week.","M":"Great! We have a variety of options. Does she have any particular interests?","W":"She loves art and drawing. Do you have any art supplies?","M":"Yes, we have several art kits. This deluxe set includes colored pencils, markers, and a sketchbook. It\'s $35.","W":"That sounds perfect! I\'ll take it. Can you gift wrap it?","M":"Of course. Gift wrapping is complimentary. Would you like a card as well?","W":"Yes, please. How much extra is the card?","M":"Cards are $3 each. We have several designs to choose from.","W":"I\'ll take one with balloons on it.","M":"Excellent choice. Your total will be $38."},"question":"What is the woman going to purchase?","options":["An art kit only","An art kit and gift wrapping","An art kit, gift wrapping, and a card","A sketchbook and markers","Colored pencils and a card"],"answer":3,"explanation":"The woman purchases the deluxe art kit ($35) with complimentary gift wrapping and adds a card ($3), making her total $38."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중하',
    distractor_score: '4',
    final_json: '{"dialogue":{"W":"Hi, I\'m looking for a birthday gift for my daughter. She\'s turning 10 next week.","M":"Great! We have a variety of options. Does she have any particular interests?","W":"She loves art and drawing. Do you have any art supplies?","M":"Yes, we have several art kits. This deluxe set includes colored pencils, markers, and a sketchbook. It\'s $35.","W":"That sounds perfect! I\'ll take it. Can you gift wrap it?","M":"Of course. Gift wrapping is complimentary. Would you like a card as well?","W":"Yes, please. How much extra is the card?","M":"Cards are $3 each. We have several designs to choose from.","W":"I\'ll take one with balloons on it.","M":"Excellent choice. Your total will be $38."},"question":"What is the woman going to purchase?","options":["An art kit only","An art kit and gift wrapping","An art kit, gift wrapping, and a card","A sketchbook and markers","Colored pencils and a card"],"answer":3,"explanation":"The woman purchases the deluxe art kit ($35) with complimentary gift wrapping and adds a card ($3), making her total $38."}'
  },
  {
    request_id: 'R-0011',
    raw_json: '{"dialogue":{"M":"Excuse me, I think there\'s a problem with my order. I asked for a veggie burger, but this has meat in it.","W":"Oh, I\'m so sorry about that. Let me check with the kitchen right away.","M":"I\'m a vegetarian, so I really can\'t eat this.","W":"I completely understand. I\'ll have them make a new veggie burger for you immediately. In the meantime, can I get you a complimentary drink while you wait?","M":"That would be nice, thank you. How long will it take?","W":"It should only be about 5 minutes. Again, I apologize for the mix-up.","M":"No problem, mistakes happen. I appreciate you handling it quickly.","W":"Of course. I\'ll also take 20% off your bill for the inconvenience."},"question":"What will the woman do for the man?","options":["Refund his entire meal","Replace his order and offer compensation","Ask him to leave the restaurant","Charge him extra for the new burger","Ignore his complaint"],"answer":2,"explanation":"The woman offers to replace the burger, provide a complimentary drink while he waits, and give 20% off his bill as compensation for the mistake."}',
    normalized_json: '{"dialogue":{"M":"Excuse me, I think there\'s a problem with my order. I asked for a veggie burger, but this has meat in it.","W":"Oh, I\'m so sorry about that. Let me check with the kitchen right away.","M":"I\'m a vegetarian, so I really can\'t eat this.","W":"I completely understand. I\'ll have them make a new veggie burger for you immediately. In the meantime, can I get you a complimentary drink while you wait?","M":"That would be nice, thank you. How long will it take?","W":"It should only be about 5 minutes. Again, I apologize for the mix-up.","M":"No problem, mistakes happen. I appreciate you handling it quickly.","W":"Of course. I\'ll also take 20% off your bill for the inconvenience."},"question":"What will the woman do for the man?","options":["Refund his entire meal","Replace his order and offer compensation","Ask him to leave the restaurant","Charge him extra for the new burger","Ignore his complaint"],"answer":2,"explanation":"The woman offers to replace the burger, provide a complimentary drink while he waits, and give 20% off his bill as compensation for the mistake."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중',
    distractor_score: '3',
    final_json: '{"dialogue":{"M":"Excuse me, I think there\'s a problem with my order. I asked for a veggie burger, but this has meat in it.","W":"Oh, I\'m so sorry about that. Let me check with the kitchen right away.","M":"I\'m a vegetarian, so I really can\'t eat this.","W":"I completely understand. I\'ll have them make a new veggie burger for you immediately. In the meantime, can I get you a complimentary drink while you wait?","M":"That would be nice, thank you. How long will it take?","W":"It should only be about 5 minutes. Again, I apologize for the mix-up.","M":"No problem, mistakes happen. I appreciate you handling it quickly.","W":"Of course. I\'ll also take 20% off your bill for the inconvenience."},"question":"What will the woman do for the man?","options":["Refund his entire meal","Replace his order and offer compensation","Ask him to leave the restaurant","Charge him extra for the new burger","Ignore his complaint"],"answer":2,"explanation":"The woman offers to replace the burger, provide a complimentary drink while he waits, and give 20% off his bill as compensation for the mistake."}'
  },
  {
    request_id: 'R-0033',
    raw_json: '{"passage":"The concept of \'urban heat islands\' refers to metropolitan areas that experience significantly higher temperatures than surrounding rural areas. This phenomenon occurs primarily due to the extensive use of concrete, asphalt, and other materials that absorb and retain heat. Additionally, the lack of vegetation in cities reduces natural cooling through evapotranspiration. Human activities such as transportation, industrial processes, and air conditioning systems also contribute to excess heat generation. The consequences of urban heat islands include increased energy consumption, elevated air pollution levels, and health risks particularly for vulnerable populations. Cities worldwide are now implementing various strategies to mitigate these effects, including increasing green spaces, using reflective building materials, and promoting sustainable urban planning practices.","question":"Which of the following is NOT mentioned as a cause of urban heat islands?","options":["Use of heat-absorbing building materials","Reduced vegetation in urban areas","Heat generated by human activities","Ocean currents affecting coastal cities","Lack of natural cooling processes"],"answer":4,"explanation":"The passage mentions concrete/asphalt (heat-absorbing materials), lack of vegetation, and human activities as causes. Ocean currents are not mentioned in the passage."}',
    normalized_json: '{"passage":"The concept of \'urban heat islands\' refers to metropolitan areas that experience significantly higher temperatures than surrounding rural areas. This phenomenon occurs primarily due to the extensive use of concrete, asphalt, and other materials that absorb and retain heat. Additionally, the lack of vegetation in cities reduces natural cooling through evapotranspiration. Human activities such as transportation, industrial processes, and air conditioning systems also contribute to excess heat generation. The consequences of urban heat islands include increased energy consumption, elevated air pollution levels, and health risks particularly for vulnerable populations. Cities worldwide are now implementing various strategies to mitigate these effects, including increasing green spaces, using reflective building materials, and promoting sustainable urban planning practices.","question":"Which of the following is NOT mentioned as a cause of urban heat islands?","options":["Use of heat-absorbing building materials","Reduced vegetation in urban areas","Heat generated by human activities","Ocean currents affecting coastal cities","Lack of natural cooling processes"],"answer":4,"explanation":"The passage mentions concrete/asphalt (heat-absorbing materials), lack of vegetation, and human activities as causes. Ocean currents are not mentioned in the passage."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중상',
    distractor_score: '4',
    final_json: '{"passage":"The concept of \'urban heat islands\' refers to metropolitan areas that experience significantly higher temperatures than surrounding rural areas. This phenomenon occurs primarily due to the extensive use of concrete, asphalt, and other materials that absorb and retain heat. Additionally, the lack of vegetation in cities reduces natural cooling through evapotranspiration. Human activities such as transportation, industrial processes, and air conditioning systems also contribute to excess heat generation. The consequences of urban heat islands include increased energy consumption, elevated air pollution levels, and health risks particularly for vulnerable populations. Cities worldwide are now implementing various strategies to mitigate these effects, including increasing green spaces, using reflective building materials, and promoting sustainable urban planning practices.","question":"Which of the following is NOT mentioned as a cause of urban heat islands?","options":["Use of heat-absorbing building materials","Reduced vegetation in urban areas","Heat generated by human activities","Ocean currents affecting coastal cities","Lack of natural cooling processes"],"answer":4,"explanation":"The passage mentions concrete/asphalt (heat-absorbing materials), lack of vegetation, and human activities as causes. Ocean currents are not mentioned in the passage."}'
  },
  {
    request_id: 'R-0034',
    raw_json: '{"passage":"Bioluminescence, the production and emission of light by living organisms, is one of nature\'s most fascinating phenomena. While commonly associated with deep-sea creatures, bioluminescence occurs across various species including fireflies, certain fungi, and some bacteria. The chemical reaction typically involves luciferin, a light-emitting molecule, and luciferase, an enzyme that catalyzes the reaction. Different organisms have evolved bioluminescence for various purposes: attracting mates, luring prey, deterring predators, or communicating with others of their species. Scientists are now exploring practical applications of bioluminescence, from developing glow-in-the-dark plants that could reduce the need for street lighting to creating sensitive detection methods for environmental pollutants.","question":"What is the main purpose of this passage?","options":["To explain how fireflies attract mates","To describe the chemical composition of luciferin","To provide an overview of bioluminescence and its applications","To argue for increased funding for bioluminescence research","To compare different bioluminescent species"],"answer":3,"explanation":"The passage provides a general overview of bioluminescence, explaining what it is, which organisms possess it, the chemistry behind it, its various purposes in nature, and potential human applications."}',
    normalized_json: '{"passage":"Bioluminescence, the production and emission of light by living organisms, is one of nature\'s most fascinating phenomena. While commonly associated with deep-sea creatures, bioluminescence occurs across various species including fireflies, certain fungi, and some bacteria. The chemical reaction typically involves luciferin, a light-emitting molecule, and luciferase, an enzyme that catalyzes the reaction. Different organisms have evolved bioluminescence for various purposes: attracting mates, luring prey, deterring predators, or communicating with others of their species. Scientists are now exploring practical applications of bioluminescence, from developing glow-in-the-dark plants that could reduce the need for street lighting to creating sensitive detection methods for environmental pollutants.","question":"What is the main purpose of this passage?","options":["To explain how fireflies attract mates","To describe the chemical composition of luciferin","To provide an overview of bioluminescence and its applications","To argue for increased funding for bioluminescence research","To compare different bioluminescent species"],"answer":3,"explanation":"The passage provides a general overview of bioluminescence, explaining what it is, which organisms possess it, the chemistry behind it, its various purposes in nature, and potential human applications."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중',
    distractor_score: '4',
    final_json: '{"passage":"Bioluminescence, the production and emission of light by living organisms, is one of nature\'s most fascinating phenomena. While commonly associated with deep-sea creatures, bioluminescence occurs across various species including fireflies, certain fungi, and some bacteria. The chemical reaction typically involves luciferin, a light-emitting molecule, and luciferase, an enzyme that catalyzes the reaction. Different organisms have evolved bioluminescence for various purposes: attracting mates, luring prey, deterring predators, or communicating with others of their species. Scientists are now exploring practical applications of bioluminescence, from developing glow-in-the-dark plants that could reduce the need for street lighting to creating sensitive detection methods for environmental pollutants.","question":"What is the main purpose of this passage?","options":["To explain how fireflies attract mates","To describe the chemical composition of luciferin","To provide an overview of bioluminescence and its applications","To argue for increased funding for bioluminescence research","To compare different bioluminescent species"],"answer":3,"explanation":"The passage provides a general overview of bioluminescence, explaining what it is, which organisms possess it, the chemistry behind it, its various purposes in nature, and potential human applications."}'
  },
  {
    request_id: 'R-0041',
    raw_json: '{"title_options":["The History of Coffee Consumption","Why Coffee Makes You Alert","The Global Coffee Trade","Coffee: From Bean to Cup","The Chemistry of Caffeine"],"passage":"Every morning, millions of people around the world start their day with a cup of coffee. But few consider the remarkable journey each coffee bean takes before reaching their cup. Coffee plants are primarily grown in tropical regions along the equator, in countries like Brazil, Vietnam, and Colombia. After harvesting, the beans undergo processing to remove the outer fruit, then are dried, sorted, and graded for quality. The green beans are then shipped to roasters worldwide, where heat transforms them into the aromatic brown beans we recognize. The roasting process is crucial, as it develops the complex flavors and compounds that make each coffee unique. Finally, the beans are ground and brewed, completing a journey that may have started thousands of miles away.","answer":4,"explanation":"The passage traces coffee\'s journey from growing regions through processing, shipping, roasting, and brewing—hence \'From Bean to Cup\' best captures this progression."}',
    normalized_json: '{"title_options":["The History of Coffee Consumption","Why Coffee Makes You Alert","The Global Coffee Trade","Coffee: From Bean to Cup","The Chemistry of Caffeine"],"passage":"Every morning, millions of people around the world start their day with a cup of coffee. But few consider the remarkable journey each coffee bean takes before reaching their cup. Coffee plants are primarily grown in tropical regions along the equator, in countries like Brazil, Vietnam, and Colombia. After harvesting, the beans undergo processing to remove the outer fruit, then are dried, sorted, and graded for quality. The green beans are then shipped to roasters worldwide, where heat transforms them into the aromatic brown beans we recognize. The roasting process is crucial, as it develops the complex flavors and compounds that make each coffee unique. Finally, the beans are ground and brewed, completing a journey that may have started thousands of miles away.","answer":4,"explanation":"The passage traces coffee\'s journey from growing regions through processing, shipping, roasting, and brewing—hence \'From Bean to Cup\' best captures this progression."}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '중',
    distractor_score: '4',
    final_json: '{"title_options":["The History of Coffee Consumption","Why Coffee Makes You Alert","The Global Coffee Trade","Coffee: From Bean to Cup","The Chemistry of Caffeine"],"passage":"Every morning, millions of people around the world start their day with a cup of coffee. But few consider the remarkable journey each coffee bean takes before reaching their cup. Coffee plants are primarily grown in tropical regions along the equator, in countries like Brazil, Vietnam, and Colombia. After harvesting, the beans undergo processing to remove the outer fruit, then are dried, sorted, and graded for quality. The green beans are then shipped to roasters worldwide, where heat transforms them into the aromatic brown beans we recognize. The roasting process is crucial, as it develops the complex flavors and compounds that make each coffee unique. Finally, the beans are ground and brewed, completing a journey that may have started thousands of miles away.","answer":4,"explanation":"The passage traces coffee\'s journey from growing regions through processing, shipping, roasting, and brewing—hence \'From Bean to Cup\' best captures this progression."}'
  },
  {
    request_id: 'R-0042',
    raw_json: '{"passage":"The ancient Egyptians developed one of the earliest forms of paper, known as papyrus, around 3000 BCE. Made from the pith of the papyrus plant that grew abundantly along the Nile River, this writing material revolutionized record-keeping and communication. The production process involved cutting the plant\'s stem into thin strips, laying them in overlapping layers, and pressing them together while still moist. The natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface. Papyrus scrolls became essential for documenting everything from religious texts to administrative records, enabling the preservation of knowledge across generations and facilitating the growth of Egyptian civilization.","question":"According to the passage, what natural element helped bind the papyrus strips together?","options":["Water from the Nile River","Sugars contained in the plant","Mud used as an adhesive","Heat from the Egyptian sun","Oils extracted from the stems"],"answer":2,"explanation":"The passage states that \'the natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface.\'"}',
    normalized_json: '{"passage":"The ancient Egyptians developed one of the earliest forms of paper, known as papyrus, around 3000 BCE. Made from the pith of the papyrus plant that grew abundantly along the Nile River, this writing material revolutionized record-keeping and communication. The production process involved cutting the plant\'s stem into thin strips, laying them in overlapping layers, and pressing them together while still moist. The natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface. Papyrus scrolls became essential for documenting everything from religious texts to administrative records, enabling the preservation of knowledge across generations and facilitating the growth of Egyptian civilization.","question":"According to the passage, what natural element helped bind the papyrus strips together?","options":["Water from the Nile River","Sugars contained in the plant","Mud used as an adhesive","Heat from the Egyptian sun","Oils extracted from the stems"],"answer":2,"explanation":"The passage states that \'the natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface.\'"}',
    validation_result: 'PASS',
    validation_log: '',
    difficulty_est: '하',
    distractor_score: '3',
    final_json: '{"passage":"The ancient Egyptians developed one of the earliest forms of paper, known as papyrus, around 3000 BCE. Made from the pith of the papyrus plant that grew abundantly along the Nile River, this writing material revolutionized record-keeping and communication. The production process involved cutting the plant\'s stem into thin strips, laying them in overlapping layers, and pressing them together while still moist. The natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface. Papyrus scrolls became essential for documenting everything from religious texts to administrative records, enabling the preservation of knowledge across generations and facilitating the growth of Egyptian civilization.","question":"According to the passage, what natural element helped bind the papyrus strips together?","options":["Water from the Nile River","Sugars contained in the plant","Mud used as an adhesive","Heat from the Egyptian sun","Oils extracted from the stems"],"answer":2,"explanation":"The passage states that \'the natural sugars in the plant acted as an adhesive, binding the strips into a smooth, durable surface.\'"}'
  }
];

async function seedItemJson() {
  try {
    await initDatabase();
    const db = getDb();

    console.log('ITEM_JSON 데이터 삽입 시작...');

    const insertStmt = db.prepare(`
      INSERT OR REPLACE INTO item_json
      (request_id, raw_json, normalized_json, validation_result, validation_log, difficulty_est, distractor_score, final_json)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `);

    let insertedCount = 0;
    for (const item of itemJsonData) {
      insertStmt.run(
        item.request_id,
        item.raw_json,
        item.normalized_json,
        item.validation_result,
        item.validation_log,
        item.difficulty_est,
        item.distractor_score,
        item.final_json
      );
      insertedCount++;
    }

    console.log(`✅ ${insertedCount}개의 ITEM_JSON 데이터 삽입 완료`);

    // 삽입된 데이터 확인
    const items = db.prepare('SELECT request_id, validation_result, difficulty_est, distractor_score FROM item_json').all();
    console.log('\n📊 삽입된 ITEM_JSON 목록:');
    items.forEach(item => {
      console.log(`  - ${item.request_id}: ${item.validation_result} (난이도: ${item.difficulty_est}, 오답매력도: ${item.distractor_score})`);
    });

    closeDatabase();
    console.log('\n데이터베이스 연결 종료');

  } catch (error) {
    console.error('시드 오류:', error);
    process.exit(1);
  }
}

seedItemJson();
